[package]
name = "morph-rs"
version = "0.1.0"
description = "Rust library for interfacing with the Morph InfiniConnect earbuds."
readme = "README.md"
keywords = ["earbuds", "bluetooth"]
categories = ["earbuds", "bluetooth"]
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
edition = "2021"
publish = false
license = "MIT"
repository = "https://github.com/morph-audio/morph-rs.git"
homepage = "https://github.com/morph-audio/morph-rs"

[features]
default = []

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
btleplug = { version = "0.10.1", features = ["serde"] }
tokio = { version = "1.21.1", features = ["full"] } 
uuid = { version = "1.1.2", features = ["v4"] }
futures = "0.3.24"