name: Push submodule update dispatch event to MorphInfiniControl repo
on: [ push, workflow_dispatch ]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Notify MorphInfiniControl repo workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: open-morphs/MorphInfiniControl
          event-type: submodule-update
          client-payload: '{"ref": "${{ github.ref }}", "module": "open-morphs/morph-rs", "branch": "main"}'
